# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Simple Chaos Spring Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        # ubuntu-latest, windows-latest, macos-latest
        jdk-version: [11]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk-version }}
    - name: Build with Maven
      run: mvn -B install --file SimpleChaos/spring/pom.xml